### ISSUE TITLE
ГОЙДА

### ISSUE THREAD

**Issue by maleyvich** [hretim/Orignal-Homigrad#1]
ИИСУС ГОВОРИЛ ПРАВДУ НО ЕМУ НИКТО НЕ ВЕРИЛ!!!!

**Comment by hretim** [comment]
иссусес

**Comment by Ziperfix2001** [comment]
А команды для ULX какие?

**Comment by uzelezz123** [comment]
> А команды для ULX какие?

huy

**Comment by magmen3** [comment]
Проблемка с навыком

**Comment by gegrman** [comment]
подскажите чо делать, скачал сборку захожу в гмод выбираю оружие, а оно трясется(контент скачал, играл по локалке)
