### ISSUE TITLE
Бинокль

### ISSUE THREAD

**Issue by Ce1azz** [hretim/Orignal-Homigrad#6]
![image](https://github.com/hretim/Orignal-Homigrad/assets/145237450/02982493-6e2a-443c-ae9a-012a82143e68)
Бинокль имеет модель камеры, из-за чего при приближении ничего не видно
![image](https://github.com/hretim/Orignal-Homigrad/assets/145237450/875145eb-8430-4b8e-9b42-2fde57c5f53a)

**Comment by uzelezz123** [comment]
пофиксил + новая модель
