### ISSUE TITLE
old view

### ISSUE THREAD

**Issue by LogineZZ** [hretim/Orignal-Homigrad#7]
хм, почему бы не выпустить старую версию прицеливания? которая была со времен Q меню для всех на сервере?

**Comment by uzelezz123** [comment]
не понимаю, о чем ты

**Comment by magmen3** [comment]
у старого хомиграда отдельный branch, выбери его и скачай

**Comment by Pisanw** [comment]
Скинь тогда

**Comment by uzelezz123** [comment]
> Скинь тогда

🤦‍♂️
